### ISSUE TITLE
It's not you, it's the people on the internet

### ISSUE THREAD

**Issue by runvnc** [danielm82/anon-test#1]
Personally I think what you did was fine.  It may not meet everyone's ideal.  But they are raking you over the coals both ways.  One popular complaint for even using React at all and not just using HTML/CSS.  But also the other way for not using enough React stuff to make a NodeComponent.   

If the company came back and said they had other candidates who did that and seemed more expert with React, to me that would be fair enough.   But what happened was the company ignored your effort and then 1000 people on reddit decided they could do it better.
They are just piling on at an opportunity to shit on someone.

What you did works.  90% of the people jumping on the "let's shit on Daniel's work" bandwagon because they could have written better commit messages probably would not have even been able to make a working solution in a reasonable amount of time.

The company did not treat you fairly or respectfully and neither did reddit.

**Comment by danielm82** [comment]
Thanks, it means a lot. I try not to take all of that personally and learn from what I can.
